import{Routes,Route,useLocation,Link}from'react-router-dom';
import{useEffect,useState,lazy,Suspense}from'react';import{Headphones}from'lucide-react';import{hydrateCatalog}from'./data/products';
import{StoreProvider,useStore}from'./context/Store';
import Header from'./components/Header';import Footer from'./components/Footer';import CompareBar from'./components/CompareBar';
const Home=lazy(()=>import('./views/Home'));const QuickOrder=lazy(()=>import('./views/QuickOrder'));const Catalog=lazy(()=>import('./views/Catalog'));const ProductPage=lazy(()=>import('./views/ProductPage'));const Cart=lazy(()=>import('./views/Cart'));const Auth=lazy(()=>import('./views/Auth'));const Dashboard=lazy(()=>import('./views/Dashboard'));const Application=lazy(()=>import('./views/Application'));const InfoPage=lazy(()=>import('./views/InfoPage'));const NotFound=lazy(()=>import('./views/NotFound'));const SupplierPage=lazy(()=>import('./views/SupplierPage'));
const AdminPanel=lazy(()=>import('./views/AdminPanel'));const AdminLogin=lazy(()=>import('./views/AdminPanel').then(m=>({default:m.AdminLogin})));
const BrandPage=lazy(()=>import('./views/DiscoveryPages').then(m=>({default:m.BrandPage})));const BrandDirectory=lazy(()=>import('./views/DiscoveryPages').then(m=>({default:m.BrandDirectory})));const CategoryPage=lazy(()=>import('./views/DiscoveryPages').then(m=>({default:m.CategoryPage})));const SupplierDirectory=lazy(()=>import('./views/DiscoveryPages').then(m=>({default:m.SupplierDirectory})));const ComparePage=lazy(()=>import('./views/MarketplaceTools').then(m=>({default:m.ComparePage})));const RFQPage=lazy(()=>import('./views/MarketplaceTools').then(m=>({default:m.RFQPage})));
function RouteLoading(){return <div className="route-loading"><span></span><span></span><span></span></div>}
function Shell(){const{pathname}=useLocation();const{toast}=useStore();const[ready,setReady]=useState(false);useEffect(()=>{hydrateCatalog();setReady(true)},[]);useEffect(()=>{window.scrollTo(0,0)},[pathname]);if(pathname.startsWith('/admin'))return <Suspense fallback={<RouteLoading/>}><Routes><Route path="/admin/login" element={<AdminLogin/>}/><Route path="/admin/*" element={<AdminPanel/>}/></Routes></Suspense>;return <><Header/><main><Suspense fallback={<RouteLoading/>}><Routes><Route path="/" element={<Home/>}/><Route path="/quick-order" element={<QuickOrder/>}/><Route path="/shop" element={<Catalog key={ready?'ready':'loading'}/>}/><Route path="/search" element={<Catalog/>}/><Route path="/new-arrivals" element={<Catalog preset="New"/>}/><Route path="/best-sellers" element={<Catalog preset="Best Seller"/>}/><Route path="/deals" element={<Catalog preset="Deal"/>}/><Route path="/products/:slug" element={<ProductPage/>}/><Route path="/cart" element={<Cart/>}/><Route path="/checkout" element={<Cart checkout/>}/><Route path="/login" element={<Auth/>}/><Route path="/apply" element={<Application/>}/><Route path="/compare" element={<ComparePage/>}/><Route path="/supplier/meridian" element={<SupplierPage/>}/><Route path="/suppliers" element={<SupplierDirectory/>}/><Route path="/brands" element={<BrandDirectory/>}/><Route path="/brand/:slug" element={<BrandPage/>}/><Route path="/category/:slug" element={<CategoryPage/>}/><Route path="/request-quote" element={<RFQPage/>}/><Route path="/account/*" element={<Dashboard/>}/><Route path="/:page" element={<InfoPage/>}/><Route path="*" element={<NotFound/>}/></Routes></Suspense></main><CompareBar/><Link className="sourcing-help" to="/contact" aria-label="Contact sourcing support"><Headphones/><span><b>Sourcing support</b><small>Talk to our distribution team</small></span></Link><Footer/>{toast&&<div className="toast" role="status">✓ {toast}</div>}</>}
export default function App(){return <StoreProvider><Shell/></StoreProvider>}
